# Site settings
title: Patrick Hammond
email: patrick dot hammond at gmail dot com
description: "The most exciting phrase to hear in science, the one that heralds new discoveries, is not 'Eureka!' but 'That's funny...' -Isaac Asimov"
baseurl: ""
url: "http://patrickhammond.com"
username: "patrickhammond"
# Build settings
markdown: kramdown
permalink: pretty
